openapi: 3.0.2
info:
  title: Pet API
  version: '1.0.0'
servers:
  - url: http://18.176.100.172:8080/v1
    description: Test server
  - url: https://dev.sample-server.com/v1
    description: Development server
  - url: https://stg.sample-server.com/v1
    description: Staging server
  - url: https://api.sample-server.com/v1
    description: Production server
paths:
  /pets/{petId}:
    get:
      tags:
        - pet
      summary: Find pet by ID
      description: Returns a single pet
      operationId: getPetById
      parameters:
        - in: path
          name: petId
          required: true
          schema:
            type: integer
          description: ID of pet to return
          example: 123
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
components:
  schemas:
    Pet:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          description: Pet ID
        name:
          type: string
          description: Pet Name