openapi: 3.0.2
info:
  title: サンプルOpenAPI仕様書
  description: |
    <h2 id="introduction">はじめに</h2>
    <h3 id="about-api">APIについて</h2>
    これはサンプルAPIのOpenAPI仕様書です。
  version: '1.0.0'
servers:
  - url: https://api.sample-server.com/v1
    description: 本番環境
  - url: https://stg.sample-server.com/v1
    description: テスト環境
paths:
  /pets/{petId}:
    get:
      tags:
        - pets
      summary: ペット情報取得
      description: id を指定して対象ペットの情報を1件取得します。
      operationId: get-pet-by-id
      parameters:
        - in: path
          name: petId
          required: true
          schema:
            type: integer
          description: 取得するペット情報のID
          example: 123
      responses:
        '200':
          description: ペット情報の取得が成功しました。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: 指定された id のペット情報が存在しません。
  /pets:
    get:
      tags:
        - pets
      summary: ペット情報一覧取得
      description: クエリ条件に合致したペット情報の一覧を取得します。
      operationId: get-pets
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
          description: 返されるペット情報の最大数
          example: 50
      responses:
        '200':
          description: ペット情報の取得が成功しました。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '400':
          description: 送信内容に不備があります。内容をご確認ください。
components:
  schemas:
    Pet:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          description: ペット情報ID
        name:
          type: string
          description: ペットニックネーム
      title: ペット情報
    Pets:
      type: array
      items:
        $ref: '#/components/schemas/Pet'
      title: ペット情報一覧